### ISSUE TITLE
Finding packages that depend upon another package.

### ISSUE THREAD

**Issue by vpenades** [emgarten/NuGet.CatalogReader#11]
Let's say I want to discover all the packages that depend on another package, for example, Newtonsoft.JSon , is it possible to do that sort of query with CatalogReader?

Thanks!

**Comment by emgarten** [comment]
This can be done with CatalogReader, I have an example here: http://emgarten.com/2017/02/05/who-depends-on-your-nuget-package-2/

**Comment by vpenades** [comment]
So, if I understand correctly, that code downloads the feed of the whole nuget gallery?

I guess if someone would be willing to use such method in production, it should need to cache the results or use other strategies to prevent downloading the whole thing for each query...

**Comment by emgarten** [comment]
It downloads all registration blobs, these are pages that contain up to 128 or so versions of a package and are split up by package id. It doesn't download the packages themselves, so it is less calls than the number of total versions.

You should definitely cache this information.

**Comment by vpenades** [comment]
I see... well, my case scenario is this: I want to make an application that has a plugin system, I wanted the application to discover the plugins at nuget by checking which packages depend on my core package.

I understand the usefulness of CatalogReader in terms if checking, from time to time, if there's dependencies of a given package... but it's definitely something that should not be done regularly, so it's not an option for me.

**Comment by emgarten** [comment]
> I wanted the application to discover the plugins at nuget by checking which packages depend on my core package.

Sounds like a neat feature. I wish there were a better way to do this, but it would take a nuget protocol change to get this info directly from a feed.
