### ISSUE TITLE
Mirroring most downloaded nugets from nuget.org

### ISSUE THREAD

**Issue by mixandmatch025** [emgarten/NuGet.CatalogReader#12]
Hi, I'd like to use _nugetmirror_ to download all nugets in nuget.org that have more than a configurable amount of downloads with their dependencies.
Is there any way to do this with the current CLI or with small changes to the existing code?

**Comment by emgarten** [comment]
Currently the search endpoint is the only way to get the download count for a package, so you would need to list everything from search, then filter on download count. Right now nugetmirror only uses the registration blobs, it doesn't use search. It could be done but it wouldn't be a small change.

There is a proposal to expose the download counts in a file which would make this easier, but it isn't implemented yet. See: https://github.com/NuGet/NuGetGallery/issues/3532

**Comment by mixandmatch025** [comment]
I see. And what about downloading all dependencies when downloading nugets?
Say when I download all packages from the last month, I'd like the cli to download their dependencies as well.

**Comment by emgarten** [comment]
Dependencies can be found in the registration blobs and also the nuspec files. It shouldn't be difficult to expand the set of things you are downloading using those.

https://github.com/emgarten/NuGet.CatalogReader/blob/b9746c085230750d7b5aea932781977885c8f034/src/NuGet.CatalogReader/CatalogEntry.cs#L212-L215

https://github.com/emgarten/NuGet.CatalogReader/blob/b9746c085230750d7b5aea932781977885c8f034/src/NuGet.CatalogReader/CatalogEntry.cs#L273-L276

**Comment by mixandmatch025** [comment]
cool, thanks
