### ISSUE TITLE
 Unable to find a service of type Catalog/3.0.0

### ISSUE THREAD

**Issue by kvpt** [emgarten/NuGet.CatalogReader#13]
Hi,

The website from which the schema is retrieved **schema.emgarten.com** seems to be down and causes an InvalidDataException when launching the app.

**Comment by emgarten** [comment]
You are seeing `InvalidDataException` when running sleet? Could you run with verbose and share the log? That url shouldn't actually be requested, so this might be due to a different issue.

**Comment by kvpt** [comment]
I use the nugetmirror executable to copy a private TFS feeds, installed with dotnet tool command.
![capture](https://user-images.githubusercontent.com/1446221/42049451-4f2d9cc6-7b06-11e8-82c2-55fa63104d88.PNG)
I have no log when executed, verbose or not.

**Comment by emgarten** [comment]
That error means that the feed doesn't have a catalog, which is what nugetmirror uses to find all packages.
