### ISSUE TITLE
Upgrading to LTS dotnet ?

### ISSUE THREAD

**Issue by Watynecc** [emgarten/NuGet.CatalogReader#17]

**Comment by emgarten** [comment]
@Watynecc which tool/library in the repo and which version of dotnet are you looking for?

I haven't gotten around to upgrading these projects yet, but if you let me know what you are targeting I can release a new version.

**Comment by Watynecc** [comment]
I wanted to install dotnet-mgcb-editor but my connection is to slow so i see your .NET application to make Mirror so i can use a France or Suisse repo to installing it

Thanks you

**Comment by emgarten** [comment]
I've updated NuGetMirror to a net5.0 dotnet tool package and it will be available on nuget.org.

https://github.com/emgarten/NuGet.CatalogReader/pull/19
