### ISSUE TITLE
XmlException: System does not support 'Windows-1252' 

### ISSUE THREAD

**Issue by arvindshmicrosoft** [emgarten/NuGet.CatalogReader#22]
Thanks for providing a very usable and useful project! I followed the quick start steps and tried to execute `NuGetMirror nupkgs https://api.nuget.org/v3/index.json -o d:\tmp` without the ignore errors switch. After a bit, it stopped due to this exception:

```
Unable to download Tabster.Core 1.0.0
        - [System.Xml.XmlException] System does not support 'Windows-1252' encoding. Line 1, position 31.
[System.Xml.XmlException] System does not support 'Windows-1252' encoding. Line 1, position 31.
```

Not sure if this is an expected exception; Using `--ignore-errors` did help. I was wondering if you could mention this switch prominently in the README here itself, or maybe include a link to [your blog post](https://emgarten.com/posts/mirroring-nuget) which gave me a clue about using `--ignore-errors`.

Environment: Microsoft Windows Server 2019 Datacenter 10.0.17763 Build 17763. en-US.

**Comment by emgarten** [comment]
@arvindshmicrosoft thanks for logging the issue

It looks like FuGet has the same problem opening the nuspec file: https://www.fuget.org/packages/Tabster.Core/1.0.0

I'll keep this open to track updating the README, it looks like it isn't possible to clone all packages without ignoring errors on some environments.

**Comment by phone2good10-pixel** [comment]
Unable to download Caching.dll 1.0.1. Retrying...
        - [System.Xml.XmlException] System does not support 'Windows-1252' encoding. Line 1, position 31.


// Register the CodePages encoding provider
`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`
