### ISSUE TITLE
Feed with authentication

### ISSUE THREAD

**Issue by kratotheron** [emgarten/NuGet.CatalogReader#24]
Is possible to add the support for the feed with authentication?
feed example: https://nuget.telerik.com/v3/index.json

**Comment by kratotheron** [comment]
Basic authentication

**Comment by emgarten** [comment]
Are you trying to mirror the feed or read the catalog?

**Comment by kratotheron** [comment]
Mirror

Distinti saluti,
Enea Del Lama
________________________________

**Comment by emgarten** [comment]
Currently auth isn't supported for NuGetMirror.  

It could be added as a feature since NuGetMirror uses the same NuGet http client as NuGet.exe

**Comment by kratotheron** [comment]
Thank you for your answer.
I can help you to implement this feature?
________________________________

**Comment by emgarten** [comment]
A PR would be great, take a look at: https://github.com/emgarten/NuGet.CatalogReader/blob/main/src/NuGet.CatalogReader/HttpReaderBase.cs

This is where it sets up the http client using the NuGet.Protocol library.

**Comment by vonj** [comment]
If ran in an Azure pipeline, would it pick up the configuration from the Nuget Authentication task automatically?

**Comment by emgarten** [comment]
@vonj no, currently there is no auth being performed

**Comment by theFra985** [comment]
I know I am a bit late but I needed the same feature so I tried adding support for loading the `HttpSource` from the local configuration through the `PackageSourceProvider` and it seems to be working (or at least the two NuGetMirror commands do). I created #30, I don't know if it might still be useful to someone.

**Comment by emgarten** [comment]
Fixed in https://github.com/emgarten/NuGet.CatalogReader/pull/30
